// @ts-nocheck
// Note: This file runs in Deno (Supabase Edge Functions), not Node.js.
// @ts-nocheck prevents standard IDE TypeScript servers from showing errors for Deno imports and globals.

import { serve } from "https://deno.land/std@0.177.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.38.4";
import crypto from "node:crypto";
import { Buffer } from "node:buffer";

// ============================================================================
// PAYSTACK WEBHOOK HANDLER
// Enterprise-Grade Security:
// 1. Constant-time signature verification (timingSafeEqual)
// 2. Idempotency lock (prevents double-billing on network retries)
// 3. Service-role elevation (bypasses RLS securely)
// 4. Immutable audit trailing
// ============================================================================

serve(async (req: Request) => {
  // 1. Validate Method
  if (req.method !== "POST") {
    return new Response("Method not allowed", { status: 405 });
  }

  try {
    // 2. Extract Paystack Signature Header
    const signature = req.headers.get("x-paystack-signature");
    if (!signature) {
      console.warn("Missing Paystack signature");
      return new Response("Unauthorized", { status: 401 });
    }

    // 3. Read raw payload for HMAC computation
    const rawBody = await req.text();
    const secret = Deno.env.get("PAYSTACK_SECRET_KEY");

    if (!secret) {
      console.error("Missing PAYSTACK_SECRET_KEY environment variable");
      return new Response("Server configuration error", { status: 500 });
    }

    // 4. Cryptographic Signature Verification (Constant-Time)
    const hash = crypto.createHmac("sha512", secret).update(rawBody).digest("hex");
    
    // Convert to buffers for timing-safe comparison to prevent cryptographic timing attacks
    const expectedBuffer = Buffer.from(hash);
    const signatureBuffer = Buffer.from(signature);

    if (expectedBuffer.length !== signatureBuffer.length || !crypto.timingSafeEqual(expectedBuffer, signatureBuffer)) {
      console.error("Signature verification failed. Potential spoofing attempt.");
      return new Response("Unauthorized", { status: 401 });
    }

    // 5. Parse Payload
    const payload = JSON.parse(rawBody);
    
    // We only care about successful charges
    if (payload.event !== "charge.success") {
      return new Response("Event ignored", { status: 200 });
    }

    const { reference, amount, currency, status } = payload.data;
    
    // For our app, the reference is likely generated by the frontend or passed in metadata
    // We assume `reference` maps to the `payments.reference` column.
    
    if (!reference) {
      console.error("Missing payment reference in payload");
      return new Response("Bad Request", { status: 400 });
    }

    if (status !== "success" || currency !== "NGN") {
      console.error(`Invalid successful charge payload. status=${status}, currency=${currency}`);
      return new Response("Invalid payment payload", { status: 400 });
    }

    // 6. Initialize Supabase Admin Client
    // Uses the Service Role Key to securely bypass Row Level Security
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // 7. Idempotency Check (Prevent Double-Billing)
    // Check if we've already processed this exact payment
    const { data: existingPayment, error: fetchError } = await supabase
      .from("payments")
      .select("id, status, student_id, amount")
      .eq("reference", reference)
      .single();

    if (fetchError && fetchError.code !== 'PGRST116') { // PGRST116 is "No rows found"
      throw fetchError;
    }

    // If payment exists and is already marked success, acknowledge and ignore
    if (existingPayment && existingPayment.status === "success") {
      console.log(`Idempotency trigger: Payment ${reference} already processed.`);
      return new Response("Already processed", { status: 200 });
    }

    if (!existingPayment) {
      // Depending on your flow, the payment row might be created by the frontend as "pending"
      // If it doesn't exist, we might need to create it using data from Paystack's metadata.
      // For safety, if we strictly require the frontend to init the payment:
      console.error(`Payment row not found for reference: ${reference}`);
      return new Response("Payment reference not found in database", { status: 404 });
    }

    const amountInNaira = amount / 100;
    const expectedAmount = Number(existingPayment.amount);
    if (Number.isFinite(expectedAmount) && expectedAmount > 0 && expectedAmount !== amountInNaira) {
      console.error(`Amount mismatch for ${reference}. expected=${expectedAmount}, got=${amountInNaira}`);
      return new Response("Payment amount mismatch", { status: 409 });
    }

    // 8. Execute Database Update. The reference has a unique index in production
    // hardening migrations, so this remains idempotent under retries.
    const { error: updateError } = await supabase
      .from("payments")
      .update({
        status: "success",
        paid_at: new Date().toISOString(),
        amount: amountInNaira,
      })
      .eq("id", existingPayment.id)
      .neq("status", "success");

    if (updateError) throw updateError;

    // 9. Immutable Audit Logging
    // Write to the audit ledger to prove this was updated securely via webhook
    const { error: auditError } = await supabase
      .from("payment_audit_log")
      .insert({
        payment_id: existingPayment.id,
        student_id: existingPayment.student_id,
        old_status: existingPayment.status,
        new_status: "success",
        changed_by: null,
        actor_type: "system",
        action: "webhook",
        note: `Verified via Paystack webhook signature. Ref: ${reference}`
      });

    if (auditError) {
      // Non-fatal, but we should log it
      console.error("Failed to write to payment_audit_log:", auditError);
    }

    console.log(`Payment ${reference} securely verified and updated.`);
    return new Response("Webhook processed successfully", { status: 200 });

  } catch (error) {
    console.error("Webhook processing error:", error);
    return new Response("Internal Server Error", { status: 500 });
  }
});
